module.exports = {
	WORDS_PARSED: 'WORDS_PARSED',
	VISITED_WORDS_CHANGED: 'VISITED_WORDS_CHANGED',
	START_GAME: 'START_GAME',
	SHOW_NEXT_QUESTION: 'SHOW_NEXT_QUESTION',
	WORD_PRESSED: 'WORD_PRESSED',
	CHANGE_LANG: 'CHANGE_LANG',
	WORDS_READY: 'WORDS_READY',
	RESET: 'RESET',
	CHANGE_LEVEL: 'CHANGE_LEVEL'
};