module.exports = {
	WORDS_PARSED: 'WORDS_PARSED',
	VISITED_WORDS_CHANGED: 'VISITED_WORDS_CHANGED',
	START_GAME: 'START_GAME',
	SHOW_NEXT_QUESTION: 'SHOW_NEXT_QUESTION',
	WORD_PRESSED: 'WORD_PRESSED',
	CHANGE_LANG: 'CHANGE_LANG',
	WORDS_READY: 'WORDS_READY',
	RESET: 'RESET',
	CHANGE_LEVEL: 'CHANGE_LEVEL',

	HOME_BUTTON_PRESSED: 'HOME_BUTTON_PRESSED',
	BROWSE_BUTTON_PRESSED: 'BROWSE_BUTTON_PRESSED',
	SETTINGS_BUTTON_PRESSED: 'SETTINGS_BUTTON_PRESSED',

	LOOKING_FOR_WORDS: 'LOOKING_FOR_WORDS',
	URL_FEATURE_REQUESTED: 'URL_FEATURE_REQUESTED',
	GUARDIAN_INFO_REQUESTED: 'GUARDIAN_INFO_REQUESTED',

	NETWORK_ERROR_OCCURRED: 'NETWORK_ERROR_OCCURRED',
	TRY_AGAIN: 'TRY_AGAIN',

	WORD_IN_BROWSER_PRESSED: 'WORD_IN_BROWSER_PRESSED',

	RANDOM_BUTTON_PRESS: 'RANDOM_BUTTON_PRESS',
	RANDOM_BUTTON_MOVE: 'RANDOM_BUTTON_MOVE',
	RANDOM_BUTTON_RELEASE: 'RANDOM_BUTTON_RELEASE',
	RANDOM_CATEGORY_SELECTED: 'RANDOM_CATEGORY_SELECTED',

	BUY_PREMIUM_VOCAB_LEVEL: 'BUY_PREMIUM_VOCAB_LEVEL'
};